#!/bin/bash

die() {
    echo $@
    exit 1
}
[ $# -eq 1 ] || die "usage: $0 <pattern>"
pat=$1
shift
for jar in $(find $* -type f -name "*.jar"); do
  m=$(jar -tvf $jar | egrep $pat)
  if [ ! -z "$m" ]; then
    echo "Found in: $jar"
    echo "$m"
  fi
done
