#!/bin/bash

mvn test -Dtest=TestDomainSocket,TestShortCircuitLocalRead,TestParallelShortCircuitRead,TestParallelRead,TestPersistBlocks,TestPeerCache,TestFileInputStreamCache,TestParallelUnixDomainRead,TestParallelShortCircuitReadNoChecksum,TestBlockReaderLocal
