#!/bin/bash

mvn test -Dtest=TestDomainSocket,TestShortCircuitLocalRead,TestParallelShortCircuitRead,TestParallelRead,TestPersistBlocks,TestPeerCache,TestParallelUnixDomainRead,TestParallelShortCircuitReadNoChecksum,TestBlockReaderLocal,TestBlockReaderLocalLegacy,TestEnhancedByteBufferAccess,TestBlockReaderFactory,TestDisableConnCache,TestDataTransferKeepalive,TestShortCircuitCache,TestBlockTokenWithDFS

# obsolete
# mvn test -Dtest=TestFileInputStreamCache,
