#!/bin/bash


die() {
    echo $@
    exit 1
}

usage() {
    cat <<EOF
runt: run native test(s) with appropriate CLASSPATH

usage: runt [options] [short-test-name]

-h: this help message
EOF
}

while getopts  "h" flag; do
    case $flag in
    h) usage; exit 0;;
    *) echo; usage; exit 1;;
    esac
done
shift $(($OPTIND - 1))

[ $# -eq 1 ] || die "must give exactly one test to run.  -h for usage."
TEST_NAME=$1

D=$(readlink -f "`dirname $0`")
[ -d $D ] || die "failed to locate enclosing directory of this script"
source $D/jarjar.sh \
    $HADOOP_HOME_BASE/share/hadoop/common \
    $HADOOP_HOME_BASE/share/hadoop/hdfs
TEST_PATH="$(find . -name $TEST_NAME -type f)"
[ "x$TEST_PATH" = "x" ] && die "failed to locate $TEST_NAME" 
$TEST_PATH || die "TEST FAILED"
exit 0
